# Generated by Django 5.1.7 on 2025-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Groceries', 'Groceries'), ('Transport', 'Transport'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Health', 'Health'), ('Travel', 'Travel'), ('Beauty', 'Beauty'), ('Clothing', 'Clothing'), ('Leisure', 'Leisure'), ('Gifts', 'Gifts'), ('Subscriptions', 'Subscriptions'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
    ]
